### ISSUE TITLE
Problema com ícone na notificação

### ISSUE THREAD

**Issue by camponuevo** [realtime-framework/CordovaPush#13]
Estou usando o framework de vocês com o Ionic e o ícone da aplicação não aparece quando a aplicação está em segundo plano e recebe notificação.

Os tamanhos de ícones que a aplicação tem hoje são: 

```
<icon density="ldpi" src="resources/android/icon/liga_36x36.png" />
<icon density="mdpi" src="resources/android/icon/liga_48x48.png" />
<icon density="hdpi" src="resources/android/icon/liga_64x64.png" />
<icon density="xhdpi" src="resources/android/icon/liga_72x72.png" />
<icon density="xxhdpi" src="resources/android/icon/liga_96x96.png" />
<icon density="xxxhdpi" src="resources/android/icon/liga_144x144.png" /> 
```

Att,

**Comment by JoaoCaixinha** [comment]
O problema estava relacionado na criação da notificação no nosso receiver. Por favor testem com a versão 0.1.16.
Ficamos a aguardar o vosso feedback.

**Comment by JoaoCaixinha** [comment]
Nova versão 0.1.17
Devem definir dois resouces com os nomes "large_notification_icon" para a icon da notificação na lista e "small_notification_icon" para o icon na barra de status, este deve ser branco com fundo transparente como indicado nas guide lines da google.

Ficamos a aguardar o vosso feedback.

**Comment by realtime-framework** [comment]
Resolvido na versão 0.1.19
