### ISSUE TITLE
Phonegap Build fails for android

### ISSUE THREAD

**Issue by silvanoAdami** [realtime-framework/CordovaPush#2]
Hi Realtime team.

I'm using Realtime plugin with an app (for android and iphone) built through "Phonegap Build".

In my config.xml file I added:

```
 <gap:plugin name="co.realtime.plugins.cordovapush" version="0.1.4" />
```

But I get the following build error:
_"Error - Two of the plugins in your app are incompatible as they both add a file with the same name. View logs to find which plugins are causing this issue."_

An Abstract of config.xml is as follows:

```
<preference name="permissions" value="none" />
<preference name="orientation" value="default" />
<preference name="target-device" value="universal" />
<preference name="fullscreen" value="false" />
<preference name="webviewbounce" value="true" />
<preference name="prerendered-icon" value="true" />
<preference name="stay-in-webview" value="false" />
<preference name="ios-statusbarstyle" value="black-opaque" />
<preference name="detect-data-types" value="true" />
<preference name="exit-on-suspend" value="false" />
<preference name="show-splash-screen-spinner" value="true" />
<preference name="auto-hide-splash-screen" value="true" />
<preference name="disable-cursor" value="false" />
<preference name="android-minSdkVersion" value="7" />
<preference name="android-installLocation" value="auto" />
<preference name="DisallowOverscroll" value="true" />

<gap:config-file parent="/manifest/application" platform="android">
    <activity android:launchMode="singleInstance" />
</gap:config-file>

<!-- GAP PLUGINS CORDOVA -->
<gap:plugin name="org.apache.cordova.battery-status"  />
<gap:plugin name="org.apache.cordova.camera"  />
<gap:plugin name="org.apache.cordova.console"  />
<gap:plugin name="org.apache.cordova.contacts"  />
<gap:plugin name="org.apache.cordova.device"  />
<gap:plugin name="org.apache.cordova.device-motion" />
<gap:plugin name="org.apache.cordova.device-orientation"  />
<gap:plugin name="org.apache.cordova.dialogs"  />
<gap:plugin name="org.apache.cordova.file"  />
<gap:plugin name="org.apache.cordova.file-transfer"  />
<gap:plugin name="org.apache.cordova.geolocation"  />
<gap:plugin name="org.apache.cordova.globalization"  />
<gap:plugin name="org.apache.cordova.inappbrowser"  />
<gap:plugin name="org.apache.cordova.media"  />
<gap:plugin name="org.apache.cordova.media-capture"  />
<gap:plugin name="org.apache.cordova.network-information"  />
<gap:plugin name="org.apache.cordova.splashscreen"  />
<gap:plugin name="org.apache.cordova.vibration"  />


<!-- GAP PLUGINS EXTERNAL -->
<gap:plugin name="com.phonegap.plugins.barcodescanner" />
<gap:plugin name="nl.x-services.plugins.launchmyapp">
    <param name="URL_SCHEME" value="XXXXXXXX" />
</gap:plugin>
<gap:plugin name="com.phonegap.plugin.statusbar" />
<gap:plugin name="com.badrit.macaddress" />
<gap:plugin name="com.simonmacdonald.telephonenumber" />
<gap:plugin name="nl.x-services.plugins.socialsharing" />
<gap:plugin name="nl.x-services.plugins.googleplus" source="plugins.cordova.io"/>

<gap:plugin name="com.phonegap.plugins.facebookconnect">
    <param name="APP_ID" value="XXXXXXXX" />
    <param name="APP_NAME" value="YYYYYYYY" />
</gap:plugin>

<gap:plugin name="nl.x-services.plugins.insomnia" />
<gap:plugin name="net.bgta.phonegap.plugin.appversion" />
<gap:plugin name="org.pushandplay.cordova.apprate" />
<gap:plugin name="co.realtime.plugins.cordovapush" version="0.1.4" />
```

I tried many modifications to plugin import but cannot find the problem.
If I remove "co.realtime.plugins.cordovapush" the build ends without errors.
Do you know which could be the problem?

Many Thanks
Silvano

**Comment by realtime-framework** [comment]
Could you provide the log referred in the issue description so we can understand with which other plugin we are in conflict?
Thanks.

**Comment by silvanoAdami** [comment]
Of course!
But it is a short log, I cannot get which is the conflict  :(

```
Build Date: 2015-08-17 19:12:24 +0000
----------------------------------------------
debug: Creating Cordova project for the Android platform:
Path: ../../../../../../project
Package: com.XXXXX
Name: YYYYYYY
Android target: android-21
Copying template files...
Running: android update project --subprojects --path "../../../../../../project" --target android-21 --
library "CordovaLib"
Resolved location of library project to: /project/CordovaLib
Updated and renamed default.properties to project.properties
Updated local.properties
No project name specified, using Activity name 'YYYYYY'.
If you wish to change it, edit the first line of build.xml.
Added file ../../../../../../project/build.xml
Added file ../../../../../../project/proguard-project.txt
Updated project.properties
Updated local.properties
No project name specified, using project folder name 'CordovaLib'.
If you wish to change it, edit the first line of build.xml.
Added file ../../../../../../project/CordovaLib/build.xml
Added file ../../../../../../project/CordovaLib/proguard-project.txt

Project successfully created.
```

It stops here without additional information.
Thank you for your reply.
Silvano

**Comment by realtime-framework** [comment]
Thanks for the reply but I'm afraid it doesn't help. Could you send us (framework@realtime.co) an example project where the issue is replicated so we can make a few tests? It would help a lot. Thanks.

**Comment by silvanoAdami** [comment]
As you requested I've sent you an email with an example project (to framework@realtime.co).
As mentioned in the email, I've found that Realtime plugin is in conflict with both plugins (phonegap build plugins) for google+ login (nl.x-services.plugins.googleplus   -   cordova-plugin-googleplus).

Thanks
Silvano

**Comment by realtime-framework** [comment]
We have changed the structure of your project (we have sent a copy to your email) and the build was successful. Can you check if it solves the issue?

**Comment by silvanoAdami** [comment]
Hi Realtime!
Thanks for the answer, I've tried to build the example you sent me with "Phonegap Build" but it gives to me the same error as before.
Could you tell me How did you build it successfully? Maybe with some other tool, outside Phonegap Build?

Thanks a lot
Silvano

**Comment by realtime-framework** [comment]
We are investigating the conflict (we could replicate it) with the cordova-plugin-googleplus plugin. We suspect it's related with the way we are adding the googleservices library.

**Comment by realtime-framework** [comment]
Building the project using Cordova CLI revealed the error:

> Failed to install 'cordova-plugin-googleplus':Error: Uh oh!
> ".../platforms/android/libs/google-play-services.jar" already exists!

We expect to publish tomorrow a new release of the plugin to solve this issue.

**Comment by silvanoAdami** [comment]
Fantastic!!!!!!!!

You are super and fast, it was really a pleasure talking with you.

Thank you a lot for the support.
Silvano

**Comment by realtime-framework** [comment]
Hi @silvanoAdami 
Please try the new Adobe PhoneGap Build Push example (using the latest CordovaPush plugin version): https://github.com/realtime-framework/phonegap-push

**Comment by silvanoAdami** [comment]
Hi Realtime!

Thank you for your support, now the problem with google+ is solved... But unfortunately (I'm sorry to say) I've found a new incompatibility problem regarding Phonegap Build - Facebook plugin and the latest Realtime CordovaPush (just Android builds).

Here the error log file:

```
   Build Date: 2015-08-25 15:38:11 +0000
   ----------------------------------------------
   Buildfile: /project/build.xml

   -set-mode-check:

   -set-release-mode:

   -release-obfuscation-check:
          [echo] proguard.config is ${proguard.config}

   -pre-build:

   -check-env:
    [checkenv] Android SDK Tools Revision 24.3.0

    -setup:
       [echo] Project Name: XXXXXXX
      [gettype] Project Type: Application

     -build-setup:
          [getbuildtools] Using latest Build Tools: 20.0.0
          [echo] Resolving Build Target for XXXXXXX...
     [gettarget] Project Target:   Android 5.0.1
     [gettarget] API level:        21
          [echo] ----------
          [echo] Creating output directories if needed...
         [mkdir] Created dir: /project/bin
         [mkdir] Created dir: /project/bin/res
         [mkdir] Created dir: /project/bin/rsObj
         [mkdir] Created dir: /project/bin/rsLibs
         [mkdir] Created dir: /project/gen
         [mkdir] Created dir: /project/bin/classes
         [mkdir] Created dir: /project/bin/dexedLibs
          [echo] ----------
          [echo] Resolving Dependencies for XXXXXXXXXX...
     [dependency] Library dependencies:
     [dependency] 
     [dependency] ------------------
     [dependency] Ordered libraries:
     [dependency] 
     [dependency] ------------------
     [dependency] Found 2 versions of android-support-v4.jar in the dependency list,
     [dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
     [dependency] All versions of the libraries must be the same at this time.
     [dependency] Versions found are:
     [dependency] Path: /project/com.phonegap.plugins.facebookconnect/client-         
     FacebookLib/libs/android-support-v4.jar
     [dependency]   Length: 758727
     [dependency]   SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
     [dependency] Path: /project/libs/android-support-v4.jar
     [dependency]   Length: 995386
     [dependency]   SHA-1: a13f8fe2c278737e2f0b6fcf00f6b2ae4034aacf

     BUILD FAILED
     /home/ec2-user/android-sdk/tools/ant/build.xml:573: Jar mismatch! Fix your dependencies

     Total time: 1 second
```

To reproduce it, you can add the following line in the config.xml project I sent you.

```
     <gap:plugin name="com.phonegap.plugins.facebookconnect">
         <param name="APP_ID" value="XXXXXXXX" />
        <param name="APP_NAME" value="YYYYYYYY" />
     </gap:plugin>
```

Searching the net, I've found this is a common problem working with android-support-v4.jar and Facebook. If you need further information I'm at your disposal.

Thank you a lot
Silvano

**Comment by realtime-framework** [comment]
Sure, we'll investigate on that. Thanks for the feedback.

**Comment by realtime-framework** [comment]
@silvanoAdami please try with version 0.1.6
https://build.phonegap.com/plugins/4345

**Comment by silvanoAdami** [comment]
Good morning!

I''ve tried with the new plugin, I've noticed that something has changed (the android-support-v4 has been added as a dependency in your project (Length and SHA-1 has changed)),  
but still I get "almost" the same error:

```
     [dependency] Ordered libraries:
     [dependency] 
     [dependency] ------------------
     [dependency] Found 2 versions of android-support-v4.jar in the dependency list,
     [dependency] but not all the versions are identical (check is based on SHA-1 only at this time).
     [dependency] All versions of the libraries must be the same at this time.
     [dependency] Versions found are:
     [dependency] Path: /project/com.phonegap.plugins.facebookconnect/client-
     FacebookLib/libs/android-support-v4.jar
     [dependency]   Length: 758727
     [dependency]   SHA-1: efec67655f6db90757faa37201efcee2a9ec3507
     [dependency] Path: /project/libs/android-support-v4.jar
     [dependency]   Length: 987314
     [dependency]   SHA-1: 9b6a9a9078af571732159b904ad423b03b7cc786
```

It seems to me that Facebook connect is using a different version of android-support-v4.jar in his plugin dependencies.
Maybe you are up to date with the latest one and they are using an older version.
Do you know if there could be a possible way to align those versions of jar?

If not, It could be possible to have, maybe a customized, unofficial version of your Cordova-Push, that uses the same version of android-support-v4.jar that Facebook connect uses?

Again, really, Thank you a lot for your patience and your help!!
Silvano

**Comment by realtime-framework** [comment]
I understand your point but it's difficult for us to be maintaining distinct versions of the plugin.

Please feel free to fork our repo and publish your own plugin using our source code and adding the android-support-v4.jar that Facebook connect uses (you can find it at https://github.com/Wizcorp/phonegap-facebook-plugin/tree/master/platforms/android/FacebookLib/libs)

Wizcorp (the phonegap-facebook-plugin maintainers) should start using the dependency instead of using the jar directly.

**Comment by silvanoAdami** [comment]
It worked forking your repo, as you suggested.
Thanks for the hint and for the fixes.
Silvano

PS: yes I agree. Wizcorp should start using dependency instead of the jar directly. I asked them to do this way.
