### ISSUE TITLE
Unable to unsubscribe

### ISSUE THREAD

**Issue by sisodiakaran** [realtime-framework/CordovaPush#5]
Hello,

Whenever I try to unsubscribe from a particular channel after some hours of subscription,  it gives me error:

```
I/ORTCPushPlugin﹕ ibt.ortc.extensibility.exception.OrtcEmptyFieldException: Channel is null or empty
```

But when I re-subscribe to same channel and try to unsubscribe at same time, it get unsubscribed successfully.

**Comment by JoaoCaixinha** [comment]
Hi,
this happens because when you want to unsubscribe a channel you must have subscribe it previously in a ortc client instance, so if you do that sequently it works, i don’t know witch platform are you testing, but in iOS after some time the operating system will kill the app, when you launch it again is a new ortc client instance that doesn’t have that channel subscription.

João Caixinha
Realtime Framework

**Comment by sisodiakaran** [comment]
Thanks, I am testing it on Android.

It means I have to resubscribe first before unsubscribe from any channel?

**Comment by realtime-framework** [comment]
Yes, it means you must be subscribing to the channel in the same ortc instance you are using to unsubscribe (in other words, the ortc instance must "know" the channel).

**Comment by sisodiakaran** [comment]
Ok, Let say I have implemented "Subscribe and then Unsubscribe method" (Because we don't have persistent Ortc JS object): It will work fine if Ortc Object was destroyed before.

But in this scenario we have a issue: If our Ortc Object still know the channel and we try to resubscribe it it throw error:

```
ORTCPushPlugin﹕ ibt.ortc.extensibility.exception.OrtcSubscribedException: Already subscribed to the channel <my_channel_name>
```

And the main issue is when this error arises nither `SUCCESS` nor `ERROR` callback called. So it must return either `SUCCESS` or `ERROR`. In short if I trigger a method it must return `promise`, without that no one can handle above error case.

**Comment by sisodiakaran** [comment]
@realtime-framework Any clue?

**Comment by JoaoCaixinha** [comment]
We are investigating this situation and let you know as soon as we got a solution.

Enviado do meu iPhone

No dia 31/08/2015, às 07:56, Karan Singh Sisodia notifications@github.com escreveu:

**Comment by JoaoCaixinha** [comment]
In fact there is no callback for subscription error, we are going to add an event for exception handling.

**Comment by sisodiakaran** [comment]
:thumbsup: gr8 to hear that. It will make the integration more easier and code blocks will be clean.

Thanks...
